# Generated by Django 3.0.1 on 2020-07-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prismx', '0002_member_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255)),
                ('aws_access_key', models.CharField(blank=True, max_length=255)),
                ('aws_secret_key', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('last_scan_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
