# Generated by Django 3.0.1 on 2020-07-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prismx', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_scan_time',
            field=models.DateTimeField(verbose_name='%m/%d/%Y %H:%M:%S'),
        ),
    ]
