# Generated by Django 3.0.1 on 2020-07-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prismx', '0004_auto_20200707_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_scan_time',
            field=models.DateTimeField(),
        ),
    ]
